language: android

#before_install:
#- yes | sdkmanager --licenses

android:
  components:
    - build-tools-21.1.2
    - build-tools-21.0.2
    - build-tools-23.0.1
    - android-18
    - android-21
    - android-23
    - extra

script:
  - rsync -avhP ./android-licenses/ "$ANDROID_HOME/licenses/"

# Override the install and test so that we don't run integration tests
install:
  - ./gradlew assemble

script:
  - ./gradlew :facebook:test -i
