language: android

android:
  components:
- tools
    - platform-tools
    - build-tools-25.0.1
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - extra

# Override the install and test so that we don't run integration tests
install:
  - ./gradlew assemble

script:
  - ./gradlew :facebook:test -i
