language: android

before_install:
- yes | sdkmanager "platforms;android-25"

android:
  components:
- tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra

# Override the install and test so that we don't run integration tests
install:
  - ./gradlew assemble

script:
  - ./gradlew :facebook:test -i
